#import = ["~/.config/alacritty/zegonix.toml"]
import = ["~/.config/alacritty/summer.toml"]

# history configuration
[scrolling]
history = 100000

# font configuration
[font]
size = 13.0

[font.normal]
family = "VictorMono Nerd Font"
style = "SemiBold"
# family = "Meslo LGS Nerd Font"
# style = "Regular"

[font.bold]
family = "VictorMono Nerd Font"
# family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font"
# family = "Mononoki Nerd Font Mono"
style = "SemiBoldItalic"

[font.bold_italic]
family = "VictorMono Nerd Font"
# family = "Mononoki Nerd Font Mono"
style = "BoldItalic"

