import = ["~/.config/alacritty/themes/zegonix.toml"]
# import = ["~/.config/alacritty/themes/summer.toml"]

# history configuration
[scrolling]
history = 100000

# font configuration
[font]
size = 13.0

[font.normal]
family = "VictorMono Nerd Font"
style = "Regular"

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font"
style = "SemiBoldItalic"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "BoldItalic"

