[colors.bright]
black = "0x6D7070"
blue = "0x1BA6FA"
cyan = "0x73FBF1"
green = "0xB8E466"
magenta = "0xA578EA"
red = "0xFF4352"
white = "0xD8D8D0"
yellow = "0xFFD750"

[colors.cursor]
cursor = "0xBBBBBB"
text = "0x202830"

[colors.normal]
black = "0x000000"
blue = "0x3883F4"
cyan = "0x009496"
green = "0x479A06"
magenta = "0xA933D3"
red = "0xFD2D2D"
white = "0xEBEBEB"
yellow = "0xDAB808"

[colors.primary]
background = "0x202830"
foreground = "0xD8D8D0"

[font]
size = 14.0

[font.bold]
family = "Victor Mono"
style = "Bold"

[font.bold_italic]
family = "Victor Mono"
style = "BoldItalic"

[font.italic]
family = "Victor Mono"
style = "SemiBoldItalic"

[font.normal]
family = "Victor Mono"
style = "SemiBold"
