format = """
\n\
[╭─ ](bold fg:zx_white)[⟨](bold fg:zx_light_magenta) \
$hostname$username \
[//](bold zx_magenta)\
$directory\
[//](bold zx_cyan)\
$git_branch[-](zx_gray)$git_status\
[//](bold zx_yellow)\
$jobs\
[⟩ ](bold zx_light_yellow)\
$fill$status\
\n[╰─](bold) $python\ 
"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = 'zegonix'

# custom colors
[palettes.zegonix]
zx_green = "#0CB653"
zx_light_green = "#4BDD94"
zx_yellow = "#4EA03D"
zx_light_yellow = "#94E85A"
zx_blue = "#2050A0"
zx_light_blue = "#72AFE3"
zx_magenta = "#E02482"
zx_light_magenta = "#FBADDD"
zx_cyan = "#15D7E5"
zx_light_cyan = "#65E7F1"
zx_dark_cyan = "#109EA8"
zx_white = "#DFDFD0"
zx_grey = "#808078"
zx_pastel_yellow = "#F1EAA2"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
disabled = false
show_always = true
style_user = "fg:zx_white"
style_root = "bold fg:zx_white"
format = '[$user]($style)'

[hostname]
disabled = false
ssh_only = true
trim_at = ''
ssh_symbol = '󱘖'
style = "bold fg:zx_white"
format = "[$ssh_symbol ]($style)"


[directory]
disabled = false
style = "fg:zx_white"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "../"
truncate_to_repo = false

[git_branch]
disabled = false
symbol = ""
style = "fg:zx_white"
format = '[$symbol $branch ]($style)'
truncation_length = 16
truncation_symbol = ">"

[git_status]
disabled = false
style = "fg:zx_white"
format = '[ $all_status$ahead_behind ]($style)'
conflicted = ' '
ahead = ' '
behind = ' '
diverged = ' '
up_to_date = ' '
untracked = ' '
stashed = ''
modified = ' '
staged = ' '
renamed = ' '
deleted = ' '
typechanged = ''

[jobs]
disabled = false
symbol_threshold = 0
number_threshold = 1
symbol = '#'
style = 'fg:zx_white'
format ="[ $symbol$number ]($style)"


[time]
disabled = true
style = "fg:zx_light_blue"
format = '[ $time ]($style)'
use_12hr = false

[status]
disabled = false
style = "fg:zx_white"
format = ' $symbol'
symbol = '[\[](bold fg:zx_pastel_yellow)[err](bold)[\]](bold fg:zx_pastel_yellow)'
success_symbol = '[\[](bold fg:zx_grey)[ok](bold)[\]](bold fg:zx_grey)'

[fill]
disabled = false
symbol = '─'
style = 'bold zx_white'

[shell]
disabled = false
style = "fg:zx_white"
format = '[\[](bold zx_gray)[$indicator]($style)[\]](bold zx_gray)'
bash_indicator = "bash"

[python]
disabled = false
symbol = ' '
style = "fg:zx_pastel_yellow"
format = '[$symbol$version ]($style)'
detect_extensions = []
detect_files = []
detect_folders = []
