format = """
\n\
[╭─ ](bold)[⟨](bold zx_light_magenta) \
$shell \
[//](bold zx_magenta)\
$username\
[//](bold zx_cyan)\
$directory\
[//](bold zx_light_yellow)\
$git_branch[-](zx_light_magenta)$git_status\
[//](bold zx_yellow)\
$jobs\
[⟩ ](bold zx_dark_cyan)\
$fill$status\
\n[╰─](bold) $python
"""

# \n[╰─](bold zx_light_magenta) 
# Disable the blank line at the start of the prompt
add_newline = false

palette = 'zegonix'

# custom colors
[palettes.zegonix]
zx_green = "#0CB653"
zx_light_green = "#4BDD94"
zx_yellow = "#5EB34D"
zx_light_yellow = "#9EDF6D"
zx_blue = "#2050A0"
zx_light_blue = "#72AFE3"
zx_magenta = "#E02482"
zx_light_magenta = "#FBADDD"
zx_cyan = "#15D7E5"
zx_light_cyan = "#65E7F1"
zx_dark_cyan = "#109EA8"
zx_white = "#DFDFD0"
zx_gray = "#808078"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
disabled = false
show_always = true
style_user = "fg:zx_white"
style_root = "fg:zx_white"
format = '[ $user ]($style)'

[directory]
disabled = false
style = "fg:zx_white"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
disabled = false
symbol = ""
style = "fg:zx_white"
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = false
style = "fg:zx_white"
format = '[ $all_status$ahead_behind ]($style)'
conflicted = ' '
ahead = ' '
behind = ' '
diverged = ' '
up_to_date = ' '
untracked = ' '
stashed = ''
modified = ' '
staged = ' '
renamed = ' '
deleted = ' '
typechanged = ''

[jobs]
disabled = false
symbol_threshold = 0
number_threshold = 1
symbol = '󰁀 '
style = 'bold fg:zx_white'
format ="[ $symbol$number ]($style)"


[time]
disabled = true
style = "fg:zx_light_blue"
format = '[ $time ]($style)'
use_12hr = false

[status]
disabled = false
style = "fg:zx_white"
format = ' [\[](bold fg:zx_green)[$symbol]($style)[\]](bold zx_green) '
symbol = '[err](bold)'
success_symbol = '[ok](bold)'

[fill]
disabled = false
symbol = '─'
style = 'bold zx_white'

[shell]
disabled = false
style = "bold fg:zx_white"
format = '[\[](bold zx_gray)[$indicator]($style)[\]](bold zx_gray)'
bash_indicator = "bash"

[python]
disabled = false
style = "bold fg:zx_blue"
format = '[\(]($style) [$virtualenv](fg:zx_white) [\)]($style) '
detect_extensions = []