[colors.primary]
background        = "0x0C0C18"
foreground        = "0xD8D8D0"
dim_foreground    = "0xA0A0A0"
bright_foreground = "0xFFFFFF"

[colors.cursor]
cursor = "0xBBBBBB"
text   = "0x202830"

[colors.normal]
black =   "0x181820"
red =     "0xE00010"
green =   "0x34AD1F"
yellow =  "0xE1D719"
blue =    "0x2B58D4"
magenta = "0xE02482"
cyan =    "0x15D7E5"
white =   "0xE0E0D0"

[colors.bright]
black =   "0x2C2C3C"
red =     "0xFF4054"
green =   "0x51E740"
yellow =  "0xF7F06E"
blue =    "0x72AFE3"
magenta = "0xFBADDD"
cyan =    "0x65E7F1"
white =   "0xFFFFFF"

[colors.dim]
black =   "0x000000" 
red =     "0xB00010" 
green =   "0x165A36" 
yellow =  "0xA5910D" 
blue =    "0x001D42" 
magenta = "0x9034B2" 
cyan =    "0x109EA8" 
white =   "0xC8C8B8" 

