#!/usr/bin/env bash

SESSION='quak'
# dont forget the '-d' option, otherwise the rest of
# the commands will get executed after the session is closed
tmux new-session -d -s "$SESSION" -n "temp"
tmux new-window -t "$SESSION" -n "dotfiles" -c $HOME/dotfiles
tmux new-window -t "$SESSION" -n "docs" -c $HOME/collection
tmux new-window -t "$SESSION" -n "stuff" -c $HOME
tmux kill-window -t "temp"
tmux attach -t "$SESSION"
